include:
  - path: compose.v2.yaml
  - path: app/connector/app/compose.yaml
  - path: data/connector/data/compose.yaml
  - path: chinook/connector/chinook/compose.yaml
  - path: countries/connector/countries/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile_inline: |-
        FROM ghcr.io/hasura/v3-engine:64d8b5b8126f593c10ffa89ba21791f326aefedd
        COPY ./build /md/
    develop:
      watch:
        - action: sync+restart
          path: engine/build
          target: /md/
    env_file:
      - engine/.env.engine
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "3000"
        target: 3000
  otel-collector:
    command:
      - --config=/etc/otel-collector-config.yaml
    environment:
      HASURA_DDN_PAT: ${HASURA_DDN_PAT}
    image: otel/opentelemetry-collector:0.104.0
    ports:
      - mode: ingress
        protocol: tcp
        published: "4317"
        target: 4317
      - mode: ingress
        protocol: tcp
        published: "4318"
        target: 4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
