services:
  countries_countries:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-graphql:v0.1.3
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $COUNTRIES_COUNTRIES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $COUNTRIES_COUNTRIES_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $COUNTRIES_COUNTRIES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8395"
        protocol: tcp
